### ISSUE TITLE
Can't resolve 'crypto'

### ISSUE THREAD

**Issue by michael-proulx** [kaleabmelkie/gatsby-source-gravatar#1]
Crypto is required by digest.js but it is missing from dependencies.

**Comment by kaleabmelkie** [comment]
![Screenshot_20210428-001230_Edge](https://user-images.githubusercontent.com/29814842/116313486-7ee8bb00-a7b6-11eb-893c-d9d5b3bca2d0.jpg)

This library has no real dependencies, certainly not digest.js.

Can you elaborate more on your usecase issue? I don't think it's realted to gastby-source-gravatar tho.

**Comment by kaleabmelkie** [comment]
Oh, if you meant [this line](https://github.com/kaleabmelkie/gatsby-source-gravatar/blob/1d1252be47af182c823e68f7854ba5915402cd13/src/lib/digest.js#L1), then [crypto is a built-in node.js library](https://nodejs.org/api/crypto.html).

**Comment by kaleabmelkie** [comment]
I found the issue, I believe it happened in your dynamic in-browser usage (i.e. `toUrl()`).

It is now fixed in [v1.0.1](https://github.com/kaleabmelkie/gatsby-source-gravatar/releases/tag/v1.0.1).

**Comment by michael-proulx** [comment]
Yes, sorry that was the issue, sorry didn't investigate more, I was on other issues but found that one
