### ISSUE TITLE
Gatsby v4 isn't supported

### ISSUE THREAD

**Issue by michael-proulx** [kaleabmelkie/gatsby-source-gravatar#2]
Gatsby v4 was released this october. 

[Migration Guide](https://www.gatsbyjs.com/docs/reference/release-notes/migrating-from-v3-to-v4/)

**Comment by kaleabmelkie** [comment]
There are four potential breaking changes for source plugins specifically according to [gatsbyjs.com/docs/reference/release-notes/migrating-source-plugin-from-v3-to-v4](https://www.gatsbyjs.com/docs/reference/release-notes/migrating-source-plugin-from-v3-to-v4)

I don't think any of these four apply here, but we can have the peer dependency support v4 too (to avoid warnings during installation).

@michael-proulx have you experienced any issues other than installation warnings in Gatsby v4?

**Comment by michael-proulx** [comment]
No other issues than installation warnings, but I'm only using `toUrl` at the moment.

**Comment by kaleabmelkie** [comment]
v1.0.2 released with the peer dependency requirement updated for gatsby v4

**Comment by michael-proulx** [comment]
Very fast, thank you!
